[pytest]
testpaths =
    functional_testing
    smoke_testing
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --browser chromium --browser firefox
markers =
    smoke: marks tests as smoke tests (deselect with '-m "not smoke"')
