@startuml
left to right direction
skin rose

actor "Employee" as Employee
actor "Tech Lead" as TechLead
actor "HR" as HR
actor "Admin" as Admin

rectangle "Hệ thống UmiCV - Tổng quan" {
  usecase "Quản lý CV cá nhân" as UC_PersonalCV
  usecase "Phê duyệt CV dự án" as UC_ProjectCV
  usecase "Quản lý chiến dịch cập nhật CV" as UC_BatchRequest
  usecase "Quản trị hệ thống & Danh mục" as UC_AdminTasks
  usecase "Xem thông báo" as UC_Notification
  usecase "Phê duyệt định dạng CV" as UC_HRApprove

  Employee --> UC_PersonalCV #blue
  Employee --> UC_Notification #blue

  TechLead --> UC_ProjectCV #purple
  TechLead --> UC_PersonalCV #purple
  TechLead --> UC_Notification #purple

  HR --> UC_BatchRequest #green
  HR --> UC_Notification #green
  HR --> UC_HRApprove #green

  Admin --> UC_AdminTasks #black
}
@enduml
